version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi121
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionString=Server=db;Database=ToyStoreDB;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql1212
    ports:
      - "1555:1433"